### PR TITLE
Update rng tests to be compatible with Random123 ver 1.13.2.

### PR DESCRIPTION
**Pull request by KineticTheory**
### Background

* All unit tests to work with Random123 version 1.13.2.

### Purpose of Pull Request

* [Fixes Redmine Issue #2078](https://rtt.lanl.gov/redmine/issues/2078)

### Description of changes

+ Set `R123_USE_CXX11` in `rng/config.h`.
+ Replace kat_cpp and ut_Engine unit tests with updated versions from the Random123 release.

### WIP

* [x] May need to have two versions of the modified tests. One that works for 1.09 and one that works for 1.13.2.
* [x] Darwin build fails with:
```
tmpxft_0001ba66_00000000-5_kat_cuda.cudafe1.cpp:(.text+0x4a28): undefined reference to `host_execute_tests(kat_instance*, unsigned int)'
```

### Status

* Reference:
  * [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
  * [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks
  * [x] Travis/Appveyor CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss3 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@alexrlongne Over the weekend, I fixed the CUDA errors and MSVC warnings.  This is finally ready for review.

BTW - I reverted some of the comment blocks to match the Random123 sources.  This made comparisons between *rng* source code and R123 source code a bit less obnoxious.

**Comment by alexrlongne** [comment]
@KineticTheory Great! Thanks, I'll look at this today.

**Comment by KineticTheory** [comment]
@along  I wouldn't spend too much time looking at the unit test changes.  I just copied chucks of source form the R123 tarfile.  That code is messy!

**Comment by alexrlongne** [comment]
@KineticTheory Is the new 64-bit preprocessor macro for architectures without `uint64_t`? Were we running into issues?

**Comment by KineticTheory** [comment]
> @KineticTheory Is the new 64-bit preprocessor macro for architectures without `uint64_t`? Were we running into issues?

Those aren't my changes.  Those are from the updated R123 release. I'm guessing they were inserted to support some light weight ARM architectures, but I don't know the details.

**Comment by alexrlongne** [comment]
@KineticTheory OK, I'm happy to merge this whenever then.

**Review by alexrlongne — APPROVED** [review]

**Comment by KineticTheory** [comment]
Please merge if you are happy with this.
